/*
 * main.c
 *
 *  Created on: Mar 27, 2023
 *      Author: moham
 */
#include "STD_TYPES.h"
#include "BIT_MATHS.h"
#include <util/delay.h>
#include "LED_interface.h"
#include "DIO_interface.h"


void main(void)
{
	DIO_voidSetPinDircetion(DIO_PORTA,DIO_PIN0,DIO_PIN_INPUT_PULLUP);
	DIO_voidSetPinDircetion(DIO_PORTA,DIO_PIN1,DIO_PIN_INPUT_PULLUP);
	DIO_voidSetPinDircetion(DIO_PORTA,DIO_PIN2,DIO_PIN_INPUT_PULLUP);
	DIO_voidSetPortDirection(DIO_PORTC,DIO_PORT_OUTPUT);
	while(1)
	{
		if( DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_LOW_PIN )
		{
			DIO_u8SetPortValue(DIO_PORTC,DIO_LOW_PORT);
			_delay_ms(500);
			DIO_u8SetPortValue(DIO_PORTC,DIO_HIGH_PORT);
			_delay_ms(500);
		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_LOW_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_LOW_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);

		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_LOW_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_HIGH_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);

		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_HIGH_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			_delay_ms(250);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			_delay_ms(250);
		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_LOW_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_HIGH_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);
			_delay_ms(300);
		}
		else if(DIO_u8GetPinValue(DIO_PORTA,DIO_PIN0)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN1)==DIO_HIGH_PIN && DIO_u8GetPinValue(DIO_PORTA,DIO_PIN2)==DIO_HIGH_PIN)
		{
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN3,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN4,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN2,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN5,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN1,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN6,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_HIGH_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_HIGH_PIN);
			_delay_ms(300);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN0,DIO_LOW_PIN);
			DIO_voidSetPinValue(DIO_PORTC,DIO_PIN7,DIO_LOW_PIN);
		}

	}
}
